import type {
  GameState, GameSettings, Player, PlayerIndex, Suit, JokerMode,
} from '@joker/engine';
import {
  createGameState, startGame, processAction, advanceToNextHand,
  calculateAIBid, chooseCardToPlay, chooseJokerPlay, isJokerCard,
  NUM_PLAYERS,
} from '@joker/engine';
import type { Room } from './room-manager';

const activeGames = new Map<string, GameState>();

export function startNewGame(room: Room): GameState {
  const players: Player[] = room.players.map(p => ({
    id: p.id,
    name: p.name,
    isAI: p.isAI,
    aiDifficulty: p.isAI ? 'medium' : undefined,
  }));

  // TODO: dealer ceremony — for now, random first dealer
  const firstDealer = Math.floor(Math.random() * NUM_PLAYERS) as PlayerIndex;

  const state = createGameState(room.code, players, room.settings, firstDealer);
  const started = startGame(state);
  activeGames.set(room.code, started);
  return started;
}

export function getGameState(roomCode: string): GameState | null {
  return activeGames.get(roomCode) || null;
}

export function handleBid(roomCode: string, playerIndex: PlayerIndex, bid: number): GameState {
  const state = activeGames.get(roomCode);
  if (!state) throw new Error('Game not found');

  const newState = processAction(state, { type: 'PLACE_BID', playerIndex, bid });
  activeGames.set(roomCode, newState);
  return newState;
}

export function handlePlayCard(roomCode: string, playerIndex: PlayerIndex, cardIndex: number): GameState {
  const state = activeGames.get(roomCode);
  if (!state) throw new Error('Game not found');

  const newState = processAction(state, { type: 'PLAY_CARD', playerIndex, cardIndex });
  activeGames.set(roomCode, newState);
  return newState;
}

export function handleJokerChoice(
  roomCode: string, playerIndex: PlayerIndex, mode: JokerMode, suit: Suit
): GameState {
  const state = activeGames.get(roomCode);
  if (!state) throw new Error('Game not found');

  const newState = processAction(state, { type: 'JOKER_CHOICE', playerIndex, mode, suit });
  activeGames.set(roomCode, newState);
  return newState;
}

export function handleNextHand(roomCode: string): GameState {
  const state = activeGames.get(roomCode);
  if (!state) throw new Error('Game not found');

  const newState = advanceToNextHand(state);
  activeGames.set(roomCode, newState);
  return newState;
}

/**
 * Filters game state for a specific player (hides other players' cards).
 */
export function getFilteredState(state: GameState, playerIndex: PlayerIndex): object {
  return {
    id: state.id,
    phase: state.phase,
    currentSet: state.currentSet,
    currentHandConfig: state.currentHandConfig,
    dealerIndex: state.dealerIndex,
    handNumber: state.handNumber,
    trump: state.trump,
    myHand: state.hands[playerIndex],
    myPlayerIndex: playerIndex,
    bidState: state.bidState,
    bids: state.bids,
    currentTrick: state.currentTrick,
    currentTurn: state.currentTurn,
    tricksWon: state.tricksWon,
    trickNumber: state.trickNumber,
    scores: state.scores,
    handScores: state.handScores,
    settings: state.settings,
    _trickWinner: (state as any)._trickWinner ?? null,
    players: state.players.map((p, i) => ({
      ...p,
      cardCount: state.hands[i]?.length || 0,
    })),
  };
}

/**
 * Process AI turns for a game. Returns states generated by AI plays.
 */
export function processAITurns(roomCode: string): GameState[] {
  const states: GameState[] = [];
  let state = activeGames.get(roomCode);
  if (!state) return states;

  let iterations = 0;
  const maxIterations = 100; // Safety limit

  while (iterations < maxIterations) {
    const currentPlayer = state.players[state.currentTurn];
    if (!currentPlayer?.isAI) break;

    if (state.phase === 'bidding') {
      const hand = state.hands[state.currentTurn];
      const bid = calculateAIBid(
        hand, state.trump, state.currentTurn,
        state.bidState.bids, state.currentHandConfig.cardsPerPlayer,
        state.dealerIndex, currentPlayer.aiDifficulty || 'medium'
      );
      state = processAction(state, { type: 'PLACE_BID', playerIndex: state.currentTurn, bid });
      activeGames.set(roomCode, state);
      states.push(state);
    } else if (state.phase === 'playing') {
      const hand = state.hands[state.currentTurn];
      const cardIndex = chooseCardToPlay(
        hand, state.currentTrick, state.trump,
        state.bids[state.currentTurn] || 0, state.tricksWon[state.currentTurn],
        hand.length, currentPlayer.aiDifficulty || 'medium'
      );

      const card = hand[cardIndex];
      state = processAction(state, { type: 'PLAY_CARD', playerIndex: state.currentTurn, cardIndex });

      if (isJokerCard(card) && state.phase === 'joker-choice') {
        const jokerDecision = chooseJokerPlay(
          hand, state.currentTrick, state.trump,
          state.bids[state.currentTurn] || 0, state.tricksWon[state.currentTurn],
          currentPlayer.aiDifficulty || 'medium'
        );
        state = processAction(state, {
          type: 'JOKER_CHOICE', playerIndex: state.currentTurn,
          mode: jokerDecision.mode, suit: (jokerDecision.suit || 'hearts') as Suit,
        });
      }

      activeGames.set(roomCode, state);
      states.push(state);
    } else {
      break;
    }

    iterations++;
  }

  return states;
}

export function setGameState(roomCode: string, state: GameState): void {
  activeGames.set(roomCode, state);
}

export function removeGame(roomCode: string): void {
  activeGames.delete(roomCode);
}
